# Generated by Django 4.0.3 on 2022-05-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('hotel', models.CharField(max_length=450)),
                ('star', models.IntegerField()),
                ('text', models.TextField()),
                ('address', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=200)),
                ('Night', models.CharField(blank=True, max_length=200, null=True)),
                ('Bed_Type', models.CharField(blank=True, max_length=300, null=True)),
                ('Person_Number', models.CharField(blank=True, max_length=300, null=True)),
                ('Price_Origin', models.CharField(blank=True, max_length=200, null=True)),
                ('Extra_Person', models.CharField(blank=True, max_length=200, null=True)),
                ('Price_Off', models.CharField(blank=True, max_length=200, null=True)),
                ('Day', models.DateField(blank=True, null=True)),
                ('Second_Day', models.DateField(blank=True, null=True)),
                ('Path', models.URLField(blank=True, max_length=400, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculation.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesm', to='calculation.information')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculation.site'),
        ),
    ]
