# Generated by Django 4.0.3 on 2022-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
